-- [1] 첫 번째 마이그레이션: 출석체크 테이블 생성
create table checkins (
  id text default gen_random_uuid()::text primary key,
  name text not null,
  date text not null,
  timestamp timestamptz default now()
);

-- [2] 두 번째 마이그레이션: 교직원 명단 테이블 생성 및 초기 데이터 주입
-- 1. 새로운 교직원 명단용 저장소(테이블) 생성
CREATE TABLE staffs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  seq_num INT NOT NULL,
  role TEXT NOT NULL,
  name TEXT NOT NULL
);

-- 2. (중요) 프론트엔드에서 즉시 수정/삭제가 가능하도록 보안(RLS) 해제 
ALTER TABLE staffs DISABLE ROW LEVEL SECURITY;

-- 3. 기존 75명의 과거 명단 데이터를 이사(Migration)
INSERT INTO staffs (seq_num, role, name) VALUES
  (1, '교장', '이정세'),
  (2, '교감', '김혜옥'),
  (3, '교사', '윤소영'),
  (4, '교사', '이재성'),
  (5, '교사', '이다솜'),
  (6, '교사', '남신애'),
  (7, '교사', '정권택'),
  (8, '교사', '노주연'),
  (9, '교사', '이제현'),
  (10, '교사', '정윤혁'),
  (11, '교사', '조윤경'),
  (12, '교무실무사', '양태모'),
  (13, '교무실무사', '양은석'),
  (14, '교사', '이경수'),
  (15, '교사', '주승현'),
  (16, '교사', '정진성'),
  (17, '교사', '김응찬'),
  (18, '교사', '송경하'),
  (19, '교사', '박민아'),
  (20, '교사', '최유빈'),
  (21, '교사', '하지선'),
  (22, '교사', '신태환'),
  (23, '교사', '조미경'),
  (24, '교사', '이소희'),
  (25, '교사', '홍인선'),
  (26, '보건교사', '박은옥'),
  (27, '상담교사', '김가람'),
  (28, '특수교사', '김한비'),
  (29, '교사', '문동민'),
  (30, '교사', '신혜서'),
  (31, '교사', '박주영'),
  (32, '교사', '윤혜인'),
  (33, '교사', '진후정'),
  (34, '교사', '김준무'),
  (35, '교사', '안유정'),
  (36, '교사', '이나래'),
  (37, '교사', '김정민'),
  (38, '교사', '정아름'),
  (39, '교사', '박시연'),
  (40, '교사', '전예빈'),
  (41, '교사', '김연하'),
  (44, '교사', '이정숙'),
  (45, '교사', '임승우'),
  (46, '교사', '김영은'),
  (47, '교사', '안미진'),
  (48, '교사', '김광연'),
  (49, '교사', '권승준'),
  (50, '교사', '신수정'),
  (51, '교사', '김소연'),
  (52, '교사', '조용범'),
  (53, '교사', '최찬수'),
  (54, '교사', '이정우'),
  (55, '교사', '노남주'),
  (56, '교사', '송소진'),
  (57, '교사', '이예림'),
  (58, '교사', '이희경'),
  (59, '교사', '박지흠'),
  (60, '교사', '이창현'),
  (61, '행정실장', '나진이'),
  (62, '행정부장', '유향숙'),
  (63, '행정계장', '한승민'),
  (64, '주무관', '유한석'),
  (65, '주무관', '노지예'),
  (66, '당직원', '김주배'),
  (67, '온세종', '양희진'),
  (68, '온세종', '신현숙'),
  (69, '온세종', '고준'),
  (70, '온세종', '이대훈'),
  (71, '온세종', '박정호'),
  (72, '온세종', '김지현'),
  (73, '온세종', '하승주'),
  (74, '온세종', '김혜영'),
  (75, '온세종', '김혜원'),
  (76, '온세종', '오다훈'),
  (77, '온세종', '박진숙');

-- [3] 세 번째 마이그레이션: 전국 단위 다중 학교(Multi-Tenant) 통합망 개편
-- 1. 학교 목록 테이블 신설 (학교 이름 중복을 원천 차단하는 UNIQUE 제약 조건 추가)
CREATE TABLE IF NOT EXISTS public.schools (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 기본 학교(세종캠퍼스고) 추가 
-- (숫자를 강제로 지정하지 않아 내부 카운터가 정상 작동하며, 이름이 겹치면 중복 생성하지 않고 무시함)
INSERT INTO public.schools (name)
VALUES ('세종캠퍼스고')
ON CONFLICT (name) DO NOTHING;

-- 3. 교직원 명단(staffs) 테이블 업그레이드
ALTER TABLE public.staffs 
ADD COLUMN IF NOT EXISTS school_id bigint REFERENCES public.schools(id) ON DELETE CASCADE;

-- (세종캠퍼스고의 실제 동적 ID를 찾아가서 자동으로 매핑시킴)
UPDATE public.staffs 
SET school_id = (SELECT id FROM public.schools WHERE name = '세종캠퍼스고') 
WHERE school_id IS NULL;

ALTER TABLE public.staffs ALTER COLUMN school_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_staffs_school_id ON public.staffs(school_id);

-- 4. 출석 기록(checkins) 테이블 업그레이드
ALTER TABLE public.checkins 
ADD COLUMN IF NOT EXISTS school_id bigint REFERENCES public.schools(id) ON DELETE CASCADE;

-- (세종캠퍼스고의 실제 동적 ID를 찾아가서 자동으로 매핑시킴)
UPDATE public.checkins 
SET school_id = (SELECT id FROM public.schools WHERE name = '세종캠퍼스고') 
WHERE school_id IS NULL;

ALTER TABLE public.checkins ALTER COLUMN school_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_checkins_school_id ON public.checkins(school_id);

-- [4] 네 번째 마이그레이션: 출석 데이터 중복 원천 차단 방어벽 (Unique Constraint)
-- "같은 학교, 같은 이름, 똑같은 날짜" 에는 절대 2개의 데이터가 들어가지 못하도록 DB 자체에 물리적인 철옹성 방어벽(UNIQUE)을 칩니다.
ALTER TABLE public.checkins ADD CONSTRAINT unique_daily_checkin UNIQUE (school_id, name, date);

-- [5] 다섯 번째 마이그레이션: Data API 접근을 위한 테이블 명시적 권한(GRANT) 부여
-- 2026년 Supabase 보안 패치에 따라 public schema의 테이블은 API 노출을 위해 명시적인 권한 부여가 필요합니다.
-- anon(익명 사용자), authenticated(로그인 사용자), service_role(서버 권한)에 권한을 부여합니다.
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

GRANT ALL PRIVILEGES ON TABLE public.checkins TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.staffs TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON TABLE public.schools TO anon, authenticated, service_role;

-- sequence (identity/serial 등)에 대한 권한 부여 (ID 자동 증가 컬럼 대응)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

